<!-- <h1>< ?php echo $block->escapeHtml($block->getWelcomeText()) ?></h1>
<h1>< ?php echo $block->getIds() ?></h1> -->
<form action="<?= $this->getURL('company/staff/index'); ?>" method="post">
    <button type="submit" name="btnView">BACK</button>  
</form>
<form action="<?php echo $this->getURL('company/staff/save')?>" method= "POST">

<input type="hidden" name="entity_id" value ="<?php echo $this->getRequest()->getparam("entity_id");?>">
    
<input type="hidden" name="parent_id" value ="<?php echo $block->getIds() ?>">
    <label>FirstName</label>
    <input type="text" name="fname" ><br>

    <label>LastName</label>
    <input type="text" name="lname"><br>

    <label>Password</label>
    <input type="text" name="password"><br>


    <label>Email</label>
    <input type="text" name="email"><br><br>
  

    <input type="submit" name="submit"><br>
</form>


