<?php
/** @var Vendor\Module\Block\CustomConfig $block */
?>
<div>
    <p>Grid View: <?php echo $block->getGridViewValue(); ?></p>
    <p>Multi Select: <?php echo $block->getMultiSelectValue(); ?></p>
    <p>Custom Button: <?php echo $block->getCustomButtonValue(); ?></p>
    <p>Options: <?php echo $block->getOptionsValue(); ?></p>
    <p>Cut off Time: <?php echo $block->getCutOffTimeValue(); ?></p>
</div>
